### ISSUE TITLE
我就看这个组件什么时候能火.....java太需要一个这种ORM组件了。

### ISSUE THREAD

**Issue by djjandyhl** [gaarason/database-all#12]

**Comment by osindex** [comment]
再加入一个migrate的脚本，更完美

**Comment by djjandyhl** [comment]
不过目前用spring boot 试了下，各种报错呀。

**Comment by xutengx** [comment]
感谢关注。
新功能后续会陆续考虑。
报错可以贴下相关信息。

**Comment by djjandyhl** [comment]
1.可能是文档的原因，按照文档操作自动生成entity和model不成功，但是我clone下来运行测试案例是可以的。
生成的BaseModel中重写父类方法  public GaarasonDataSource getProxyDataSource() 是错的，
我改为public GaarasonDataSource getGaarasonDataSource() 后可编译通过。
2.spring boot启动报错。似乎要在配置文件中加入雪花算法的配置才能启动成功，否则无法启动spring boot。

**Comment by xutengx** [comment]
这个问我已经发现了
1.  文档没有及时的更新
2. 后面会增加一个默认参数
3. 是有使用一个包扫描的库，似乎在打成jar后会有问题，会在近期修复它。

**Comment by xutengx** [comment]
就上面的问题, 新发布了个版本
