### ISSUE TITLE
希望尽量和Eloquent设计的api保持一致，这样有助于使用过Eloquent的人，更简单的上手，也不容易引起歧义。

### ISSUE THREAD

**Issue by hawind** [gaarason/database-all#22]
还想提一个建议，希望尽量和Eloquent设计的api保持一致，这样有助于使用过Eloquent的人，更简单的上手，也不容易引起歧义。毕竟目前在其他语言中，都有Eloquent的实现，在我个人看来，Eloquent就是对ORM的一次重新定义，特别是在JAVA里。
另外我们知道，在laravel中的api中，对每一个方法的命名，每一个功能的实现，都经过反复的推敲，据作者所说，有时候为了一个命名都会消耗几天的时间。其实能在java中看到这个现实是很高兴的，对那些JPA+Hibernate、mybatis等框架表示要抓狂的感觉。我坦白我是刚转到java不久，没有那些沉重的历史包袱，特别深恶痛觉把sql写到xml中的方式。以上观点，仅代表自己，不接受反驳。

```
public Record<T, K> findOrNew(Object id) {
      Record<T, K> first = this.newQuery().where(this.getPrimaryKeyColumnName(), id).first();
        if (first != null) {
            return first;
        } else {
            return this.newRecord();
        }
}

public Record<T, K> firstOrNew(T entity) {
        Record<T, K> first = this.newQuery().where(entity).first();
        if (first != null) {
            return first;
        } else {
            Record<T, K> tkRecord = this.newRecord();
            tkRecord.getEntity(entity);
            return tkRecord;
        }
 }
 ```

就如上面两个方法，是我自己在BaseModel里面加的。
1、findOrNew是传入PrimaryKey值，获取记录，这样既简单又好理解。
2、firstOrNew是传入实体然后进行查询，一般情况下，除非知道实体里的值，才会实现。但是实际情况。我们从POST请求接收到的就是实体，这个时候不能作为where的参数，当然在我自己的项目中firstOrNew是有机会出场的，比如要多条件查询一个记录，就显得非常方便了，但是平时并不需要这样处理， 其实本项目内部已经有find方法的实现了。

**Comment by hawind** [comment]
两种语言确实区别不小，坦白说，能做成这样，其实已经很了不起了。
另外再提一个小问题，我发现find方法只能接受long类型是否可以像where这样接受不同的类型呢

**Comment by xutengx** [comment]
谢谢。
目前find方法接受的主键参数的数据类型，由`模型`和`实体`的泛型确定的（且他们2者的类型需要保持一致）;
2.10.0 中额外增加了 `find(Object id)`

**Comment by hawind** [comment]
感谢感谢，然后就是那些keyBy，pluck，还有获取model.getOriginal，model.getDirty()，这些有计划增加吗

**Comment by xutengx** [comment]
关于`model.getOriginal`等在模型上的操作，后续会增加。
关于`keyBy`等在集合上的操作，这边先想一下，因为一开始是觉得和`stream`功能重复了，就么有去弄。

**Comment by hawind** [comment]
好的好的，感谢感谢。其实这些都是为了减少代码量

**Comment by xutengx** [comment]
2.11.0 在查询结果集(`RecordList`)中增加部分集合操作方法，

**Comment by hawind** [comment]
谢谢😊

**Comment by xutengx** [comment]
ok
