### ISSUE TITLE
实体为LocalDateTime时在2.9.0查询报错

### ISSUE THREAD

**Issue by hawind** [gaarason/database-all#23]
实体为LocalDateTime时在2.9.0查询报错
![image](https://user-images.githubusercontent.com/11567857/139508370-fe7708c5-cc12-4004-963b-85166954461c.png)

**Comment by xutengx** [comment]
需要提供下model和entity类，与调用的service

**Comment by hawind** [comment]
实体定义
![image](https://user-images.githubusercontent.com/11567857/139560541-7efc3760-a412-4a93-80f8-53b0e3dcf00d.png)

调用，很普通的调用什么条件也没有传
![image](https://user-images.githubusercontent.com/11567857/139560562-9aad127e-53dd-40c3-a7e3-acfda36a45a9.png)

这里有个问题，我没使用此包带的
@Table、@Column、但是使用了@Primary，因为发现不使用这个没办法使用find等函数，获取不了主键。

**Comment by xutengx** [comment]
需要提供下完成的异常堆栈信息，主要是包含完成的`Caused by:`部分

**Comment by hawind** [comment]
今天测试好像又对了，有点神奇，抱歉！

**Comment by hawind** [comment]
实体使用@Primary后，插入数据主键自动生成这样了

message : [Data truncation: Out of range value for column 'id' at row 1] sql : [insert into `channel`(`id`,`name`,`key`,`thumbnail`,`status`,`weight`,`parent_id`) values("462028348164407296","帮助","help","","0","0","0")]

**Comment by hawind** [comment]
另外是否应该加入@Transient类似注解跳过实体赋值，要不然查询就报错。提交也报错。

**Comment by xutengx** [comment]
需要确认情况：
1. 实体中“LocalDateTime”类型的属性，对应的数据库列，是不是nullable；
2. 实体中“LocalDateTime”类型的属性，对应的数据库列，是不是存在列的值为NULL；
3. 数据库中`channel`表的主键，是不是 非 bigint unsigned 类型；

**Comment by hawind** [comment]
1.实体在3楼有截图
2.日期列可能存在Null，这个不敢保证没有。这个应该要兼容吧。
3.主键应该不是unsigned，我也不想使用雪花算法，我只想使用普通的自增，递增而已。

**Comment by hawind** [comment]
而且主键感觉还必须long类型吗，这个也是有点不太好，有些表本来就小

**Comment by xutengx** [comment]
关于主键，`@Primary(idGenerator = IdGeneratorType.NEVER)`可关闭程序中的主键策略。

**Comment by xutengx** [comment]
2.10.0 增加呢对于数据库`null`的兼容性。但是还是不建议数据库允许null存在，这样会造成程序的歧义。
比如 数据库字段是 a,b,c ; 定义的对应的实体entity中有对应的属性 A,B,C; 当 a,b,c 在数据库中可能会为null的背景下，我们看到一个实体对象的属性 ｛A=123,B=null,C=null｝时，难以区分这条记录在是 `select a from table`查询出来的，还是`select a,b,c from table`但数据库中的b,c值为null导致的。

**Comment by hawind** [comment]
嗯，一般来说null字段都是用于文本，日期一般也有可能是null的，id都是不为空。看要求，至少不能让程序报错。null也不代表就是不对嘛

**Comment by xutengx** [comment]
是的
