### ISSUE TITLE
数据库中 unsigned bitint 类型 能否配置成 允许 Long类型接收

### ISSUE THREAD

**Issue by missing-u** [gaarason/database-all#3]

**Comment by xutengx** [comment]
可以，如果是 unsigned bigint 的话，超过了 Long.MAX_VALUE，在1.0.10中代码生成中加强了对这部分的支持（gaarason.database.query.range.mysql.MysqlNumericRange）。

**Comment by missing-u** [comment]
![image](https://user-images.githubusercontent.com/8327028/81182493-6f3df880-8fe0-11ea-87a6-20d8ba309261.png)
问下怎么配置

**Comment by missing-u** [comment]
![image](https://user-images.githubusercontent.com/8327028/81182643-a7453b80-8fe0-11ea-8486-15831d02dad1.png)
目前依旧在报错

**Comment by xutengx** [comment]
2.0.0 已修复
