### ISSUE TITLE
请问可否支持重写关联关系？

### ISSUE THREAD

**Issue by Lazybin** [gaarason/database-all#32]
比如我想在belongsto里面需要用通过两个组合外键的形式来关联查询父表中的信息。但是好像不支持多列。请问我是否有办法重写BelongsToQueryRelation来达到我的目的呢？谢谢

**Comment by xutengx** [comment]
你好，这个目前不支持。

**Comment by Lazybin** [comment]
请问我重写了一个新的BelongsToQueryRelation 怎么来让他加载我重写的类呢？还是目前只能在源代码里直接改？

**Comment by xutengx** [comment]
在你的源代码里面编写同名类 gaarason.database.eloquent.relation.BelongsToQueryRelation,  他的优先级会先于其他 maven 依赖.

**Comment by xutengx** [comment]
4.7.0 中，增加了对自定义关联关系的支持，可以自定义注解和解释器。这样的情况下，使用体验和预置的注解体验一样

**Comment by Lazybin** [comment]
谢谢！
