### ISSUE TITLE
使用record.getEntity()时会报 WARN  java.lang.NullPointerException 

### ISSUE THREAD

**Issue by bedrownedfish** [gaarason/database-all#33]
我是刚从laravel 转过来的。刚接触框架，是我那里没配置好吗

**Comment by xutengx** [comment]
你好，可以贴一下代码

**Comment by bedrownedfish** [comment]
![image](https://user-images.githubusercontent.com/22672067/208026011-34711281-e049-4493-a6a9-067d12e0c14d.png)
我做了异常拦截，，但是这样是不是不太好

**Comment by xutengx** [comment]
find() 在数据为空时会返回 null ，在 java 中对null调用任意方法， 会触发 NullPointerException。

有2种常见做法 
1 . 使用提供 findOrFail() ，在数据为空时会触发专用异常 EntityNotFoundException ，在异常处理处处理 EntityNotFoundException 这个专用异常。
2. 对 find() 返回值做判断  
```
record = mode.find(id); 

if( record == null ){
// ...
}
// ...
```

**Comment by bedrownedfish** [comment]
好的 好的 明白，，多谢指导
