### ISSUE TITLE
新插入数据 调用save 方法 插入后没有返回 id

### ISSUE THREAD

**Issue by missing-u** [gaarason/database-all#4]

**Comment by xutengx** [comment]
如果方便，可以贴下代码片段

**Comment by missing-u** [comment]
![image](https://user-images.githubusercontent.com/8327028/80557160-99078600-8a08-11ea-9240-22e834ef4206.png)

**Comment by xutengx** [comment]
是的，目前只会执行一次 insert ，并赋值通过程序插入的已知的属性；
而并没有执行 新的查询或者获取id之类的操作；
所以 由数据库产生的数据 都是未知的。

**Comment by missing-u** [comment]
这个可以像 laravel 那样么 
laravel 插入数据后 会把生成的 id 重新赋值给对象

**Comment by missing-u** [comment]
那 怎么 get last insert id 呢

**Comment by xutengx** [comment]
最近一次会增加这个能力，在此之前可能需要手动查询，或者使用库里面的雪花算法生成主键。

**Comment by xutengx** [comment]
2.0.0 已支持

**Comment by van-chin** [comment]
@xutengx  需要怎么获取 save 之后的 id 呢，我找不到使用方法

**Comment by xutengx** [comment]
使用ORM方式 即( https://github.com/gaarason/database-all/issues/4#issuecomment-620964597 ) 这中方式插入数据库的, 会自动赋值到对象 record 中, 即 record.getEntity() 与 record.toObject() 的对象上都会有 id.   当然, 前提是数据库支持该功能
