### ISSUE TITLE
调用 where 方法 报错 parameter index out of range (2 > number of parameters, which is 1)

### ISSUE THREAD

**Issue by missing-u** [gaarason/database-all#5]
![image](https://user-images.githubusercontent.com/8327028/80496942-6758d580-899c-11ea-9129-64d7d3b8d1a7.png)

**Comment by missing-u** [comment]
![image](https://user-images.githubusercontent.com/8327028/80496877-57d98c80-899c-11ea-9e7a-ab209795eea0.png)

**Comment by missing-u** [comment]
![image](https://user-images.githubusercontent.com/8327028/80497120-a0914580-899c-11ea-9592-3c73ceab41fb.png)

**Comment by missing-u** [comment]
![image](https://user-images.githubusercontent.com/8327028/80497215-b999f680-899c-11ea-8de1-69eadd642680.png)

**Comment by missing-u** [comment]
![image](https://user-images.githubusercontent.com/8327028/80497317-da624c00-899c-11ea-9b80-80366fa5a65d.png)

**Comment by xutengx** [comment]
这个问题,,将在最近的一个版本(1.0.11)中修复.

**Comment by missing-u** [comment]
这个问题可以优先修复么 着急用

**Comment by xutengx** [comment]
ok, 今天内
