### ISSUE TITLE
是否支持类似 laravel 中 with的功能 另外 关系模型的文档没有示例

### ISSUE THREAD

**Issue by missing-u** [gaarason/database-all#8]

**Comment by missing-u** [comment]
否则 paginate 取出来的列表页 

如果涉及到关联信息的话 

需要额外查询 会导致效率很低

**Comment by xutengx** [comment]
目前还不支持 with 类似的用法，关联关系尚在施工中。

**Comment by missing-u** [comment]
建议高优 with 生产环境没with 效率太低了

**Comment by xutengx** [comment]
with 相关用法更新了，并且支持无线级，与自动查询优化，欢迎提出宝贵意见。
